In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [6]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [8]:
from sklearn.preprocessing import MinMaxScaler   #KNN에선 min-max정규화 진행함
scaler=MinMaxScaler()
df['sepal_length']=scaler.fit_transform(df[['sepal_length']])
df['sepal_width']=scaler.fit_transform(df[['sepal_width']])
df['petal_length']=scaler.fit_transform(df[['petal_length']])
df['petal_width']=scaler.fit_transform(df[['petal_width']])
df.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0      0.222222     0.625000      0.067797     0.041667  setosa
1      0.166667     0.416667      0.067797     0.041667  setosa
2      0.111111     0.500000      0.050847     0.041667  setosa
3      0.083333     0.458333      0.084746     0.041667  setosa
4      0.194444     0.666667      0.067797     0.041667  setosa
5      0.305556     0.791667      0.118644     0.125000  setosa
6      0.083333     0.583333      0.067797     0.083333  setosa
7      0.194444     0.583333      0.084746     0.041667  setosa
8      0.027778     0.375000      0.067797     0.041667  setosa
9      0.166667     0.458333      0.084746     0.000000  setosa

In [10]:
X=df[['sepal_length','sepal_width','petal_length','petal_width']]  #독립변수
y=df['species']  #종속변수
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=11)

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [12]:
model=KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [13]:
pred=model.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,pred)
print(acc)

0.9111111111111111


In [17]:
mat=confusion_matrix(y_test,pred)  #성능평가
print(mat)

# 예측 0	예측 1	예측 2
# 실제 0	14	0	0
# 실제 1	0	12	2
# 실제 2	0	2	15

# 클래스 0: 14개를 정확하게 맞춤
# 클래스 1: 12개를 정확하게 맞춤
# 클래스 2: 15개를 정확하게 맞춤

# 오분류된 경우 (비대각선 값)
# 클래스 1의 샘플 2개가 클래스 2로 잘못 예측됨
# 클래스 2의 샘플 2개가 클래스 1로 잘못 예측됨

[[14  0  0]
 [ 0 12  2]
 [ 0  2 15]]


In [16]:
rep=classification_report(y_test,pred)
print(rep)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.86      0.86      0.86        14
   virginica       0.88      0.88      0.88        17

    accuracy                           0.91        45
   macro avg       0.91      0.91      0.91        45
weighted avg       0.91      0.91      0.91        45



# SVM

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix

In [38]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [40]:
d_mean=df['Age'].mean()
df['Age'].fillna(d_mean,inplace=True)

<ipython-input-40-06c29a351684>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(d_mean,inplace=True)


In [41]:
d_mode=df['Embarked'].mode()
df['Embarked'].fillna(d_mode[0],inplace=True)

<ipython-input-41-cdf43fcc7acf>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(d_mode[0],inplace=True)


In [42]:
df['FamilySize']=df['SibSp']+df['Parch']

In [45]:
onehot_sex=pd.get_dummies(df['Sex'])  #원-핫 인코딩(크기기준X)
df=pd.concat([df,onehot_sex],axis=1)

onehot_embarked=pd.get_dummies(df['Embarked'])
df=pd.concat([df,onehot_embarked],axis=1)

In [46]:
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex        Age  \
0                            Braund, Mr. Owen Harris    male  22.000000   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                             Heikkinen, Miss. Laina  female  26.000000   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                           Allen, Mr. William Henry    male  35.000000   
5                                   Moran, Mr. James    male  29.699118   
6                            McCarthy, Mr. Timothy J    male  54.000000   
7                     Palsson, Master. Gosta Leonard    male   2.000000   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000   

   SibSp  Parch            Ticket     Fare Cabin Embarked  FamilySize  female  \
0      1      0         A/5 21171   7.2500   NaN        S           1   False   
1      1      0          PC 17599  71.2833   C85        C           1    True   
2      0      0  STON/O2. 3101282   7.9250   NaN        S           0    True   
3      1      0            113803  53.1000  C123        S           1    True   
4      0      0            373450   8.0500   NaN        S           0   False   
5      0      0            330877   8.4583   NaN        Q           0   False   
6      0      0             17463  51.8625   E46        S           0   False   
7      3      1            349909  21.0750   NaN        S           4   False   
8      0      2            347742  11.1333   NaN        S           2    True   
9      1      0            237736  30.0708   NaN        C           1    True   

    male      C      Q      S  
0   True  False  False   True  
1  False   True  False  False  
2  False  False  False   True  
3  False  False  False   True  
4   True  False  False   True  
5   True  False   True  False  
6   True  False  False   True  
7   True  False  False   True  
8  False  False  False   True  
9  False   True  False  False

In [47]:
X=df[['Pclass','Age','Fare','FamilySize','female','male','C','Q','S']]  #독립변수
y=df['Survived']  #종속변수

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=11)

In [49]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(623, 9)
(268, 9)
(623,)
(268,)


In [50]:
model=svm.SVC(kernel='rbf')
model.fit(X_train,y_train)

SVC()

In [51]:
pred=model.predict(X_test)

In [56]:
mat=confusion_matrix(y_test,pred)  #성능평가
print(mat)
#         예측 0  예측 1
# 실제 0	 162     14
# 실제 1	  67      25

[[162  14]
 [ 67  25]]


In [54]:
rpt=classification_report(y_test,pred)
print(rpt)

              precision    recall  f1-score   support

           0       0.71      0.92      0.80       176
           1       0.64      0.27      0.38        92

    accuracy                           0.70       268
   macro avg       0.67      0.60      0.59       268
weighted avg       0.68      0.70      0.66       268

