### Numpy

In [6]:
import numpy as np

In [14]:
city =['seoul','busan','ulsan']
print(city[0])
print(type(city))

seoul
<class 'list'>


In [10]:
city=np.array(['seoul','busan','ulsan'])
print(city[0])
print(type(city))

seoul
<class 'numpy.ndarray'>


In [18]:
arr=np.array([2,4,6,8,10])
print(arr)
print(type(arr))
print(arr.dtype)

[ 2  4  6  8 10]
<class 'numpy.ndarray'>
int32


### 리스트와 넘파이 비교

In [20]:
#리스트형태
a=[1,2,3]
b=[2,4,6]
print(a+b)

[1, 2, 3, 2, 4, 6]


In [24]:
#print(a*b)  #리스트 곱하기 계산불가

In [26]:
print(a*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [28]:
print(a[1]+b[1])

6


In [33]:
#넘파이 형태
a=np.array([1,2,3])
b=np.array([2,4,6])
print(a+b)
print(a*b)

[3 6 9]
[ 2  8 18]


In [41]:
c=np.array([1,2,3,4,5,6,7,8,9])
# print(f"2단:", c*2)
for i in range(2,10):
    print(f"{i}단:", c*i)

2단: [ 2  4  6  8 10 12 14 16 18]
3단: [ 3  6  9 12 15 18 21 24 27]
4단: [ 4  8 12 16 20 24 28 32 36]
5단: [ 5 10 15 20 25 30 35 40 45]
6단: [ 6 12 18 24 30 36 42 48 54]
7단: [ 7 14 21 28 35 42 49 56 63]
8단: [ 8 16 24 32 40 48 56 64 72]
9단: [ 9 18 27 36 45 54 63 72 81]


In [49]:
res=c*5
print(res)
print(type(res))

lres=res.tolist()  #넘파이를 리스트로 변환
print(type(lres))

[ 5 10 15 20 25 30 35 40 45]
<class 'numpy.ndarray'>
<class 'list'>


In [55]:
import numpy as np

#체질량지수(BMI)
heights=np.array([170,155,160])
weights=np.array([65,45,55])

bmi=weights/(heights/100)**2
print("BMI:", bmi)

BMI: [22.49134948 18.73048907 21.484375  ]


In [65]:
#과목별 학생별 성적
#axis=0:세로방향(열)
#axis=1:가로방향(행)

#행:학생별,  열:과목별
scores=np.array([[85,90,88,95],
                [92,87,85,89],
                [78,85,91,87]])
#과목별 평균
subject_mean=scores.mean(axis=0)
print("과목별 평균:", subject_mean)

#학생별 평균
student_mean=scores.mean(axis=1)
print("학생별 평균:",  student_mean)

#정규화
nm1=scores-subject_mean
print(nm1)

과목별 평균: [85.         87.33333333 88.         90.33333333]
학생별 평균: [89.5  88.25 85.25]
[[ 0.          2.66666667  0.          4.66666667]
 [ 7.         -0.33333333 -3.         -1.33333333]
 [-7.         -2.33333333  3.         -3.33333333]]


In [79]:
#학생들의 점수(행:학생, 열:과목)
scores=np.array([[90,85,88,75],
                [85,92,87,98],
                [88,86,91,90]])

#과목별 가중치(40%, 30%, 30%)
w=np.array([0.4,0.3,0.2, 0.1])
wscore=scores*w
print(wscore)

#가중치 반영도니 학생별 평균점수
fscore=wscore.sum(axis=1)  #학생별
print(fscore)

[[36.  25.5 17.6  7.5]
 [34.  27.6 17.4  9.8]
 [35.2 25.8 18.2  9. ]]
[86.6 88.8 88.2]


In [95]:
#할인율 적용된 상품가격
price=np.array([12000,35000,8000,45000,28000])
sale=np.array([0.1,0.2,0.05,0.3,0.15])  #할인율
pricesale=price*(1-sale)
print(pricesale)

[10800. 28000.  7600. 31500. 23800.]


In [147]:
#할인조건:10만원미만10%, 20만원미만 15%, 20만원이상 20%할인
prices=np.array([50000,150000,250000,80000,120000])
sale=np.array([])
for price in prices:
    if price < 100000:
        sale = np.append(sale,0.1)
    elif price < 200000:
        sale = np.append(sale,0.15)
    else:
        sale = np.append(sale,0.2)
# print(sale)

pricesale=prices*(1-sale)
print("할인된 가격:", pricesale)

할인된 가격: [ 45000. 127500. 200000.  72000. 102000.]


In [169]:
#할인조건:10만원미만10%, 20만원미만 15%, 20만원이상 20%할인
prices=np.array([50000,150000,250000,80000,120000])

def get_final_rate(price):
    if price < 100000:
        return 0.1
    elif price < 200000:
        return 0.15
    else:
        return 0.2
        
discounts=np.array([get_final_rate(price) for price in prices])

pricesale=prices*(1-discounts)
print("할인된 가격:", pricesale)

할인된 가격: [ 45000. 127500. 200000.  72000. 102000.]


In [179]:
#5일간 3개 도시의 온도(섭씨)
temps_c=np.array([[25,27,26,24,23],  #서울
                  [28,30,29,27,26],  #부산
                  [22,24,23,21,20]]) #강릉
#섭씨-->화씨: (C*9/5)+32

temps_f=(temps_c*9/5)+32
print("화씨 온도:\n", temps_f)

화씨 온도:
 [[77.  80.6 78.8 75.2 73.4]
 [82.4 86.  84.2 80.6 78.8]
 [71.6 75.2 73.4 69.8 68. ]]


In [193]:
clothing_prices=np.array([25000,60000,15000,80000,120000])
clothing_discounts=np.array([15,25,10,50,20])  #할인율

discount_f=1-(clothing_discounts/100)
# print(discount_f)
print("할인된금액:",clothing_prices*discount_f)

할인된금액: [21250. 45000. 13500. 40000. 96000.]


In [197]:
#3개 지점 일주일 매출 데이터
import numpy as np

sales = np.array([[520000, 480000, 510000, 690000, 620000, 750000, 510000],  # 1호점
                  [480000, 460000, 490000, 670000, 580000, 710000, 490000],  # 2호점
                  [590000, 520000, 550000, 720000, 650000, 780000, 540000]])
daily_avg=sales.mean(axis=0)
print(daily_avg)
performance=(sales/daily_avg*100)-100   #평균 대비 퍼센트
print("요일별 평균 대비 성과(%):\n", performance)

[530000.         486666.66666667 516666.66666667 693333.33333333
 616666.66666667 746666.66666667 513333.33333333]
요일별 평균 대비 성과(%):
 [[-1.88679245 -1.36986301 -1.29032258 -0.48076923  0.54054054  0.44642857
  -0.64935065]
 [-9.43396226 -5.47945205 -5.16129032 -3.36538462 -5.94594595 -4.91071429
  -4.54545455]
 [11.32075472  6.84931507  6.4516129   3.84615385  5.40540541  4.46428571
   5.19480519]]


## 0차원 배열(스칼라)
- 하나의 데이터값을 가진 배열

In [208]:
arr=np.array(12)
print(arr)
print(type(arr))
#shape():배열이 무슨 차원으로 구성되어 있는지 보여줌
print(np.shape(arr))  #0차원에서는 반환값이 없음

12
<class 'numpy.ndarray'>
()


### 1차원 배열(벡터)
- 넘파이 배열의 가장 기본적 배열
- 1차원 배열은 파이썬의 리스트와 동일한 형태

In [211]:
import numpy as np
arr=np.array([2,4,6,8,10])
print(arr)
print(np.shape(arr))

[ 2  4  6  8 10]
(5,)


In [231]:
print(np.zeros(5))  #0으로 채워진 1차원 배열 생성
print(np.ones(5))
print(np.empty(5))  #빈 배열 생성
print(np.arange(5)) #0부터 5개 숫자 생성[0 1 2 3 4]

arr=np.empty(5)
arr[:]=np.arange(1,6)
print(arr)

print(np.arange(2,20,3))  #2부터 19까지 step:3
print(np.linspace(0,100,num=5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]
[1. 2. 3. 4. 5.]
[ 2  5  8 11 14 17]
[  0.  25.  50.  75. 100.]


In [233]:
scores=np.array([90,80,100,85,90])
print(scores)
scores=np.zeros(5)
print(scores)

[ 90  80 100  85  90]
[0. 0. 0. 0. 0.]


In [235]:
#5명의 출석 상태를 1로 초기화
num_students=5
attendance=np.ones(num_students)

#결석처리(두번째 학생 결석)
attendance[1]=0
print("Updated Attendance:", attendance)

Updated Attendance: [1. 0. 1. 1. 1.]


### 2차원 배열(매트릭스: 행렬)
- 2차원 배열을 행렬이라고 함
- 행과 열로 구성된 배열

In [250]:
import numpy as np
arr=np.array([
    [2,4,6],
    [1,3,5]
])
print(arr)
print(np.shape(arr))  

[[2 4 6]
 [1 3 5]]
(2, 3)


In [252]:
print(len(arr))  #행 수
print(len(arr[0])) #열 수
print(arr.ndim)  #배열의 차원 수
print(arr.shape) #배열의 크기(튜플로 반환)

2
3
2
(2, 3)


### 3차원 배열(텐서)
- 3차원 배열은 2차원 배열을 몇 번 사용하는지에 따라 깊이 달라짐

In [259]:
arr=np.array([
    [[111,112,113],[121,122,123]],
    [[211,212,213],[221,222,223]],
    [[311,312,313],[321,322,323]],
    [[411,412,413],[421,422,423]]
])
print(arr)
print(np.shape(arr))

[[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 223]]

 [[311 312 313]
  [321 322 323]]

 [[411 412 413]
  [421 422 423]]]
(4, 2, 3)


In [261]:
print(len(arr))  #깊이(층)
print(len(arr[0])) #행 개수
print(len(arr[0][0]))  #열 개수

4
2
3


### reshape(배열의 재구성)-배열의 크기 변경

In [267]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

newl=np.reshape(arr,(4,3))
print(newl)

new3=newl.flatten()
print(new3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [269]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### 배열의 차원수 확장
- newaxis사용해 기본 배열크기(차원수) 확장 가능
- newaxis:크기를 한 차원 늘림
- np.newaxis로 새로운 축 추가할 때, 그 축 크기는 항상 1

In [278]:
new=np.array([1,2,3,4,5,6])
print(new)
print(new.shape)
newarr=new[np.newaxis, :]
print(newarr)
print(newarr.shape)

newarr2=new[:, np.newaxis]
print(newarr2)
print(newarr2.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [288]:
arr=np.array([1,2,3,4])
row_vector=arr[np.newaxis, :]
col_vector=arr[:, np.newaxis]

print(arr.shape)

print(row_vector.shape)
print(row_vector)
print(col_vector.shape)
print(col_vector)

(4,)
(1, 4)
[[1 2 3 4]]
(4, 1)
[[1]
 [2]
 [3]
 [4]]


### 넘파이 인덱싱

In [293]:
#1차원 인덱싱
arr=np.array([2,4,6,8])
print(arr[1]+arr[3])

12


In [295]:
#2차원 인덱싱
arr=np.array([[2,4,6],[1,3,5]])
arr

array([[2, 4, 6],
       [1, 3, 5]])

In [297]:
arr[0,1]

4

In [301]:
#3차원 인덱싱
arr=np.array([[[11,12,13],[14,15,16]],
             [[21,22,23],[24,25,26]]])
arr   #(2,2,3)

array([[[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [303]:
print(arr[1,0,0])

21


### 음수 인덱싱

In [306]:
arr=np.array([2,4,6,8])
arr[-1]

8

In [310]:
arr=np.array([[2,4,6],[1,3,5]])
arr[1,-2]

3

### 조건에 맞는 요소 인덱싱
- (True,False)값으로 표시

In [314]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [316]:
arr[arr<5]

array([1, 2, 3, 4])

In [318]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [322]:
arr[(arr > 3) & ( arr < 9 )]

array([4, 5, 6, 7, 8])

In [326]:
arr=np.array([10,11,12,13,14,15,16,17,18,19])
print(arr[-1])
print(arr[0:3])  #시작번호:끝번호+1
print(arr[4:])
print(arr[4:6]) #4번부터 6번앞까 지
print(arr[4:-4])

19
[10 11 12]
[14 15 16 17 18 19]
[14 15]
[14 15]


In [344]:
#학생들의 시험 점수 분석(3반 4명의 학생)
scores=np.array([[85,90,75,88],
                 [92,86,78,95],
                 [89,91,84,82]])

#1반의 모든 학생 점수, 인원수, 총점, 평균
print("1반 전체 점수:", scores[0])
print("1반 전체 인원:", len(scores[0]),"명")
print("1반 전체 합계:", np.sum(scores[0]))
print("1반 전체 평균:", np.mean(scores[0]))

print("각 반의 첫 번째 학생:", scores[:,0])

1반 전체 점수: [85 90 75 88]
1반 전체 인원: 4 명
1반 전체 합계: 338
1반 전체 평균: 84.5
각 반의 첫 번째 학생: [85 92 89]


In [352]:
inventory=np.array([[50,30,20,40],
                    [45,25,15,35],
                    [55,35,25,45]])
low_stock=inventory[inventory<20]
print(low_stock)
low_stock1=np.where(inventory<20)
print(low_stock1)
print(list(zip(low_stock1[0],low_stock1[1])))

[15]
(array([1], dtype=int64), array([2], dtype=int64))
[(1, 2)]
